version: '3.8'
services:
  api: 
    container_name: api
    image: api-oracle-nestjs
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    command: npm start
    ports:
      - "3000:3000"        
    environment:
      ENV: production