/**
* CREATE Table API001_USU MNEMONIC
*/
CREATE TABLE APP001.API001_USU (
    USU_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    USU_CPF VARCHAR2(11) NOT NULL UNIQUE,
    USU_PFL VARCHAR2(45) NOT NULL,
    USU_EML VARCHAR2(200) NOT NULL UNIQUE,
    USU_FRT_NAM VARCHAR2(45) ,
    USU_LST_NAM VARCHAR2(4000),
    USU_STS NUMBER(1,0) DEFAULT 1,
    USU_CRT_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    USU_UPD_AT TIMESTAMP NULL,
    USU_PSW VARCHAR2(60),
    PRIMARY KEY (USU_ID)
);
COMMIT;

/**
* CREATE Table API001_TSK MNEMONIC
*/
CREATE TABLE APP001.API001_TSK (
    TSK_ID RAW(16) default SYS_GUID() PRIMARY KEY,
    TSK_NAM VARCHAR2(11) NOT NULL,
    TSK_DSC VARCHAR2(300) NOT NULL,
    TSK_STS NUMBER(1,0) DEFAULT 0,
    TSK_USU_ID NUMBER(12) NOT NULL CONSTRAINT FK_API001_TSK_USU_ID REFERENCES API001_USU(USU_ID),
    TSK_CRT_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    TSK_UPD_AT TIMESTAMP NULL
);
COMMIT;
INSERT INTO APP001.API001_USU (USU_CPF,USU_PFL, USU_EML, USU_FRT_NAM, USU_LST_NAM,USU_STS, USU_PSW) 
VALUES ('77444621063', 'admin', 'admin@system.com', 'Admin', 'System', 1, '$2b$10$IVOsdVthIS6d3t/CE5vwv.IdBGzSvrqx7e3HPyA48e1pgCTMcgzD6');
COMMIT;