/**
* CREATE Table API001_TSK MNEMONIC
*/
CREATE TABLE APP001.API001_TSK (
    TSK_ID RAW(16) default SYS_GUID() PRIMARY KEY,
    TSK_NAM VARCHAR2(11) NOT NULL,
    TSK_DSC VARCHAR2(300) NOT NULL,
    TSK_STS NUMBER(1,0) DEFAULT 0,
    TSK_USU_ID NUMBER(12) NOT NULL CONSTRAINT FK_API001_TSK_USU_ID REFERENCES API001_USU(USU_ID),
    TSK_CRT_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    TSK_UPD_AT TIMESTAMP NULL
);